export const bondBasketData = {
  gameDuration: 60,
  spawnIntervalMs: 800,
  spawnIntervalStartMs: 22000,
  spawnIntervalEndMs: 18640,
  maxConcurrentItems: 4,
  spawnYMin: -140,
  spawnYMax: -28,
  fallSpeedStart: 20,
  fallSpeedEnd: 50,
  fallSpeedVariance: 0.45,
  warmupSeconds: 10,
  accelerationExponent: 1.8,
  typeChangeIntervalMs: 5000,
  passingScore: 8,
  scoring: {
    correct: 2,
    wrong: -2,
    missed: -1,
  },
  basketTypes: ['ionic', 'covalent', 'metallic', 'hydrogen'],
  fallingItems: [
    { id: 'nacl', label: 'NaCl', type: 'ionic' },
    { id: 'mgo', label: 'MgO', type: 'ionic' },
    { id: 'h2', label: 'H₂', type: 'covalent' },
    { id: 'h2o', label: 'H₂O', type: 'covalent' },
    { id: 'fe', label: 'Fe', type: 'metallic' },
    { id: 'cu', label: 'Cu', type: 'metallic' },
    { id: 'hf', label: 'H–F', type: 'hydrogen' },
    { id: 'h2o_hbond', label: 'H₂O···H₂O', type: 'hydrogen' },
  ],
};
